name: Build APK

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main
  workflow_dispatch:  # Можно запустить вручную

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip curl default-jdk openjdk-11-jdk
          pip install buildozer cython

      # Настройка Android SDK
      - name: Setup Android SDK
        run: |
          # Создать директорию для Android SDK
          mkdir -p ~/Android/Sdk
          export ANDROID_HOME=~/Android/Sdk
          export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin

          # Скачать cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          # Принять лицензии и установить компоненты
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;25.2.9519653"

      # Настройка Buildozer
      - name: Initialize Buildozer
        run: |
          echo "[app]" > buildozer.spec
          echo "title = LoRa Messenger" >> buildozer.spec
          echo "package.name = lora_messenger" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
          echo "version = 0.1" >> buildozer.spec
          echo "requirements = python3,kivy,serial" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
          echo "osx.kivy_version = 2.1.0" >> buildozer.spec
          echo "android.arch = arm64-v8a" >> buildozer.spec
          echo "android.api = 30" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.ndk_api = 21" >> buildozer.spec
          echo "android.sdk_path = ~/Android/Sdk" >> buildozer.spec
          echo "android.ndk_path = ~/Android/Sdk/ndk/25.2.9519653" >> buildozer.spec

      # Сборка APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # Загрузка APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
